blog_create:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /

blog_homepage:
    path:     /blog
    defaults: { _controller: BlogBundle:Blog:Index }

blog_about:
    path:     /about
    defaults: { _controller: BlogBundle:About:About }