<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /*Find quantity of posts*/
    public function findAllBlogCont(){
        $query = $this->createQueryBuilder("b");
        $query->select("count(b)");
        return $query->getQuery()->getOneOrNullResult();
    }

    /*Show a specified number of posts in main page*/
    public function findBlog(array $context = []){
        $query = $this->createQueryBuilder("b");
        $query->select("b");
        $query->setMaxResults(3);   
        $query->orderBy("b.id", "DESC");
        $page = 0;
        if(isset($context["page"]) && is_numeric($context["page"]) && $context["page"]>1){
            $page = 3 * ($context["page"]-1);
        }

        $query->setFirstResult($page);
        return $query->getQuery()->getResult();
    }
}