create_prod:
    path:     /
    defaults: { _controller: "BlogBundle:Post:Prod" }
    methods:  GET

create_showPost:
    path:     /showme/{id}
    defaults: { _controller: "BlogBundle:Post:ShowPOst" }
    methods:  GET

create_index:
    path:     /admin
    defaults: { _controller: "BlogBundle:Post:index" }
    methods:  GET

create_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Post:show" }
    methods:  GET

create_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Post:new" }
    methods:  [GET, POST]

create_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Post:edit" }
    methods:  [GET, POST]

create_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Post:delete" }
    methods:  DELETE